set locators and formatters conditional on split_freq
AmpersandTV/pymc3-hmm pull request #51
Opened 2020-10-30 19:02 UTC by xjing76

just added in conditional statement for `matplotlib` locators and formatters base on `split_freq`

2020-10-30 20:09 UTC, brandonwillard requested changes
Looks like you need to run `make black` to fix some formatting issues (and amend the commit, of course); otherwise, this `pd.to_timedelta` approach looks good.

2020-10-30 20:09 UTC, brandonwillard commented on pymc3_hmm/utils.py
> +        if pd.to_timedelta(f'1{split_freq}')/300 <pd.to_timedelta('1H'):
This needs some sort of check, in case there is already a number specified in the `split_freq` (e.g. `split_freq = "10d"`).

2021-02-22 16:30 UTC, dgerlanc commented
Does this relate to #50?

@Veganveins

2021-02-22 21:01 UTC, Veganveins commented
> Does this relate to #50?
> 
> @Veganveins

yes -- definitely looks like it

2021-02-25 16:09 UTC, Veganveins commented
should we close this given that we merged [#59](https://github.com/AmpersandTV/pymc3-hmm/pull/59) ?

2021-03-16 21:40 UTC, closed without merging